money={
    "500":0,
    "200":0,
    "100":0,
    "50":0,
    "20":0,
    "10":0,
    "5":0,
    "2":0,
    "1":0,
    "0.5":0,
    "0.2":0,
    "0.1":0,
    "0.05":0,
    "0.02":0,
    "0.01":0
}
form=document.getElementsByTagName("form")[0]
for (var key in money) {
    console.log(form)
    form.innerHTML+=key+"zł:"
    input=document.createElement("input")
    input.setAttribute("type","number")
    input.setAttribute("min","0")
    input.setAttribute("step","1")
    input.setAttribute("name",key)
    input.setAttribute("value",'0')
    input.setAttribute("class","money")
    form.appendChild(input)
    form.innerHTML+="<br>"
}
submit=document.createElement("input")
submit.setAttribute("type","submit")
submit.setAttribute("value","Sprawdź/Napraw")
submit.setAttribute("id","submit")
form.appendChild(submit)